PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

SELECT ?id ?shorthand ?label ?description 
WHERE {
	?term rdfs:label ?label ;
	<http://purl.obolibrary.org/obo/IAO_0000115> ?description ;
	<http://www.geneontology.org/formats/oboInOwl#id> ?id;
	FILTER (lang(?label) = 'ja')
	FILTER (lang(?description) = 'ja')
	OPTIONAL {?term <http://www.geneontology.org/formats/oboInOwl#shorthand> ?shorthand}
}
ORDER BY ?id
